import { PDFDocument, PDFPage, StandardFonts, rgb, PDFFont } from "pdf-lib";

const red=rgb(.74,.04,.11), gray=rgb(.55,.55,.55), black=rgb(.08,.08,.08), white=rgb(1,1,1);
const text=(v:unknown)=>String(v??"").trim()||"No registra";
const date=(v:unknown)=>v?new Date(String(v)).toLocaleDateString("es-CO",{timeZone:"America/Bogota"}):"No registra";
function fit(s:unknown,n=62){return text(s).slice(0,n)}
function label(page:PDFPage,font:PDFFont,value:string,x:number,y:number,size=8,color=black){const safe=(value==="Verificación"||value==="VERIFICACIÓN"?"VERIF.":value).replaceAll("Lectura ↑","Lect. A").replaceAll("Lectura ↓","Lect. B").replaceAll("LECTURA ↑","LECT. A").replaceAll("LECTURA ↓","LECT. B").replaceAll("↑"," arriba").replaceAll("↓"," abajo");page.drawText(safe,{x,y,size,font,color})}
function box(page:PDFPage,font:PDFFont,title:string,value:unknown,x:number,y:number,w:number,h=30){page.drawRectangle({x,y,width:w,height:h,borderColor:gray,borderWidth:.7});label(page,font,title.toUpperCase(),x+5,y+h-10,6.2);label(page,font,fit(text(value),Math.floor(w/5.2)),x+5,y+7,8)}
function section(page:PDFPage,bold:PDFFont,title:string,y:number){page.drawRectangle({x:32,y,width:531,height:16,color:gray});label(page,bold,title,36,y+4,8,white)}
function footer(page:PDFPage,font:PDFFont,pageNo:number,total:number,code:string){label(page,font,`${pageNo} de ${total}`,285,19,7);label(page,font,code,455,19,7)}
function header(page:PDFPage,font:PDFFont,bold:PDFFont,title:string,code:string,pageNo:number,total:number){label(page,bold,"JD Soluciones Biomédicas",190,806,12,red);label(page,font,"NIT. 1129522276-5  Bogotá D.C.  Móvil: 3166258230",160,791,7);label(page,font,"E-mail: jdsolucionesbiomedicas@outlook.com",190,780,7);page.drawLine({start:{x:32,y:772},end:{x:563,y:772},thickness:1,color:black});label(page,bold,title,155,750,12);box(page,bold,title.includes("Hoja")?"Hoja de Vida":"Informe de Servicio",code,32,714,531,24);footer(page,font,pageNo,total,title.includes("Hoja")?"F-HV-001.FOR r.0 2025-04":"F-SREP-001.FOR r.0 2025-04")}
function checks(page:PDFPage,font:PDFFont,items:string[],selected:string[],x:number,y:number){items.forEach((v,i)=>{const px=x+i*102;label(page,font,v,px,y,7);page.drawRectangle({x:px+74,y:y-1,width:8,height:8,borderColor:black,borderWidth:.7});if(selected.some(s=>s.toLowerCase()===v.toLowerCase()))label(page,font,"X",px+75.5,y,7)})}

export async function equipmentPdf(item:any,company:any,image?:{bytes:Uint8Array;type:string}){
 const doc=await PDFDocument.create(),page=doc.addPage([595,842]),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);header(page,font,bold,"Hoja de Vida Equipos Biomédicos",item.code,1,1);
 let y=700;section(page,bold,"IDENTIFICACIÓN Y ESPECIFICACIONES DEL EQUIPO",y);y-=35;box(page,font,"Nombre del equipo",item.name,32,y,258);box(page,font,"Modelo",item.model,300,y,263);y-=36;box(page,font,"Fabricante / Marca",item.brand,32,y,258);box(page,font,"Número de serie",item.serialNumber,300,y,263);y-=36;box(page,font,"Fecha de compra",date(item.purchaseDate),32,y,258);box(page,font,"Nombre del propietario",item.ownerName||company?.name,300,y,263);y-=36;box(page,font,"Ubicación",item.location,32,y,258);box(page,font,"Contacto",item.contactName||company?.representative,300,y,263);
 y-=25;section(page,bold,"DATOS DEL PROVEEDOR",y);y-=35;box(page,font,"Nombre",item.supplierName,32,y,258);box(page,font,"Dirección",item.supplierAddress,300,y,263);y-=36;box(page,font,"Teléfono",item.supplierPhone,32,y,258);box(page,font,"Correo electrónico",item.supplierEmail,300,y,263);
 y-=25;section(page,bold,"INFORMACIÓN METROLÓGICA",y);y-=35;box(page,font,"¿Requiere verificación?",item.requiresMetrology?"Sí":"No",32,y,258);box(page,font,"Frecuencia de calibración",item.calibrationFrequency,300,y,263);
 y-=25;section(page,bold,"DOCUMENTACIÓN TÉCNICA",y);y-=20;let docs:string[]=[];try{docs=JSON.parse(item.technicalDocuments||"[]")}catch{}checks(page,font,["Planos","Manual Servicio","Manual Mantto","Ficha Técnica","Listado Partes"],docs,38,y);
 y-=25;section(page,bold,"EVIDENCIA FOTOGRÁFICA",y);y-=132;page.drawRectangle({x:32,y,width:531,height:126,borderColor:gray,borderWidth:.7});if(image){try{const img=image.type.includes("png")?await doc.embedPng(image.bytes):await doc.embedJpg(image.bytes);const d=img.scale(Math.min(1,220/img.width,112/img.height));page.drawImage(img,{x:297-d.width/2,y:y+7,width:d.width,height:d.height})}catch{label(page,font,"Evidencia fotográfica adjunta al registro",205,y+58,8)}}
 y-=18;label(page,bold,"OBSERVACIONES",32,y,8,red);label(page,font,fit(item.observations,110),32,y-17,8);page.drawLine({start:{x:32,y:y-22},end:{x:563,y:y-22},thickness:.5,color:gray});page.drawLine({start:{x:32,y:y-40},end:{x:563,y:y-40},thickness:.5,color:gray});
 label(page,font,"Firma: ______________________________",180,69,8);label(page,bold,"Especialista Biomédico: JEYSON MENDOZA M.",170,54,8);label(page,font,"Reg. Invima: RH-202211-01547",215,42,7);return doc.save();
}

export async function servicePdf(report:any,item:any,company:any){const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);const p1=doc.addPage([595,842]),p2=doc.addPage([595,842]);header(p1,font,bold,"Informe de Servicio de Mantenimiento",report.code,1,2);header(p2,font,bold,"Informe de Servicio de Mantenimiento",report.code,2,2);let y=700;section(p1,bold,"DATOS DEL CLIENTE Y DEL SERVICIO",y);y-=34;box(p1,font,"Nombre",company?.name,32,y,258);box(p1,font,"Fecha",date(report.serviceDate),300,y,263);y-=35;box(p1,font,"Contacto",company?.representative,32,y,258);box(p1,font,"Ciudad",company?.city,300,y,263);y-=35;box(p1,font,"Celular",report.clientPhone||company?.phone,32,y,258);box(p1,font,"Hora inicio / Hora fin",`${report.startTime||"--:--"} / ${report.endTime||"--:--"}`,300,y,263);y-=25;section(p1,bold,"INFORMACIÓN DEL EQUIPO",y);y-=35;box(p1,font,"Descripción",report.equipmentDescription||item.name,32,y,258);box(p1,font,"Modelo",report.equipmentModel||item.model,300,y,263);y-=35;box(p1,font,"Marca",report.equipmentBrand||item.brand,32,y,258);box(p1,font,"Número de serie",report.equipmentSerial||item.serialNumber,300,y,263);y-=25;label(p1,bold,"1. Tipo de servicio",32,y,9);checks(p1,font,["Correctivo","Preventivo","Instalación","Garantía","Diagnóstico"],[report.serviceType],32,y-18);y-=50;label(p1,bold,"2. Descripción de Falla",32,y,9);box(p1,font,"Descripción",report.summary,32,y-52,531,42);y-=88;box(p1,font,"Código de falla reportada",report.reportedFaultCode,32,y,258);box(p1,font,"Código de falla encontrada",report.foundFaultCode,300,y,263);y-=28;label(p1,bold,"3. Detalle del Servicio",32,y,9);label(p1,font,`¿Incluyó verificación de calibración? ${report.calibrationVerified?"Sí":"No"}`,32,y-18,8);box(p1,font,"Detalle",report.serviceDetail,32,y-70,531,44);y-=105;if(report.calibrationVerified){label(p1,bold,"4. Verificación de Calibración",32,y,9);const cols=["Base","Lectura ↑","Lectura ↓","Error","Tol.","Verificación","Referencia","Lectura ↑","Lectura ↓","Error","Tol.","Verificación"];cols.forEach((c,i)=>box(p1,font,c,"",32+i*44.25,y-31,44.25,28));let m:any={};try{m=JSON.parse(report.calibrationMeasurements||"{}") }catch{};for(let r=0;r<4;r++)cols.forEach((_,i)=>box(p1,font,"",m[`cal_${r}_${i}`]||"",32+i*44.25,y-59-r*22,44.25,21));y-=155}label(p1,bold,"OBSERVACIONES",32,y,8,red);label(p1,font,fit(report.observations,110),32,y-18,8);
 label(p2,bold,"RESPONSABLE DEL SERVICIO",70,650,9);label(p2,font,"Firma: __________________________",55,590,8);label(p2,bold,`Especialista Biomédico: ${text(report.technician)}`,55,570,8);label(p2,font,"Reg. Invima: RH-202211-01547",85,555,7);label(p2,bold,"RECIBE A SATISFACCIÓN",355,650,9);label(p2,font,"Firma: __________________________",335,590,8);label(p2,font,`Nombre: ${text(report.receivedBy)}`,335,570,8);return doc.save()}

function cop(v:number){return new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(v)}
function words(n:number):string{n=Math.round(n);if(n===0)return"Cero";const u=["","Uno","Dos","Tres","Cuatro","Cinco","Seis","Siete","Ocho","Nueve","Diez","Once","Doce","Trece","Catorce","Quince","Dieciséis","Diecisiete","Dieciocho","Diecinueve","Veinte","Veintiuno","Veintidós","Veintitrés","Veinticuatro","Veinticinco","Veintiséis","Veintisiete","Veintiocho","Veintinueve"],t=["","","Treinta","Cuarenta","Cincuenta","Sesenta","Setenta","Ochenta","Noventa"],h=["","Ciento","Doscientos","Trescientos","Cuatrocientos","Quinientos","Seiscientos","Setecientos","Ochocientos","Novecientos"];const small=(x:number):string=>x<30?u[x]:x<100?`${t[Math.floor(x/10)]}${x%10?" y "+u[x%10]:""}`:x===100?"Cien":`${h[Math.floor(x/100)]}${x%100?" "+small(x%100):""}`;if(n<1000)return small(n);if(n<1e6)return `${n<2000?"Mil":small(Math.floor(n/1000))+" Mil"}${n%1000?" "+small(n%1000):""}`;if(n<1e9)return `${n<2e6?"Un Millón":words(Math.floor(n/1e6))+" Millones"}${n%1e6?" "+words(n%1e6):""}`;return `${words(Math.floor(n/1e9))} Mil Millones${n%1e9?" "+words(n%1e9):""}`}
function line(page:PDFPage,font:PDFFont,bold:PDFFont,labelText:string,value:unknown,x:number,y:number,w=330){page.drawRectangle({x,y,width:w,height:18,borderColor:rgb(.78,.78,.78),borderWidth:.8});label(page,bold,labelText,x+3,y+5,7);label(page,font,fit(value,55),x+83,y+5,7)}
export async function quotationPdf(q:any,items:any[],logoBytes?:Uint8Array){const doc=await PDFDocument.create(),page=doc.addPage([595,842]),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);if(logoBytes){try{const logo=await doc.embedPng(logoBytes),d=logo.scale(Math.min(1,135/logo.width,75/logo.height));page.drawImage(logo,{x:40,y:735,width:d.width,height:d.height})}catch{}}
 label(page,bold,"COTIZACIÓN",385,770,25,rgb(.92,0,0));label(page,bold,"NIT:",42,718,9);label(page,font,"1129522276-5",65,718,9);label(page,bold,"Matrícula Comercial:",140,718,9);label(page,font,"03951953",245,718,9);label(page,bold,"Email:",42,700,8);label(page,font,"jdsolucionesbiomedicas@outlook.com",78,700,8);label(page,bold,"Dirección:",42,683,8);label(page,font,"Carrera 9 # 18-33 Loc. 21, Bogotá D.C.",90,683,8);label(page,bold,"Móvil:",42,666,8);label(page,font,"3166258230 - 3204731030",75,666,8);line(page,font,bold,"COTIZACIÓN N°:",q.code,370,716,180);line(page,font,bold,"FECHA:",date(q.createdAt),370,698,180);line(page,font,bold,"VÁLIDO HASTA:",`${q.validDays||10} días`,370,680,180);
 page.drawRectangle({x:42,y:642,width:330,height:18,color:gray});label(page,bold,"DATOS CLIENTE",170,647,9,white);line(page,font,bold,"NOMBRE:",q.companyName||q.customerName,42,624);line(page,font,bold,"NIT:",q.customerNit,42,606);line(page,font,bold,"DIRECCIÓN:",q.customerAddress,42,588);line(page,font,bold,"CONTACTO:",q.contactName||q.customerName,42,570);line(page,font,bold,"E-MAIL:",q.email,42,552);
 let y=524;const widths=[42,342,76,78],heads=["CANT","DESCRIPCIÓN","COSTO UNIT","SUBTOTAL"];let x=42;heads.forEach((v,i)=>{page.drawRectangle({x,y,width:widths[i],height:20,color:gray,borderColor:white,borderWidth:1});label(page,bold,v,x+4,y+6,8,white);x+=widths[i]});y-=18;items.slice(0,12).forEach(item=>{x=42;const vals=[String(item.quantity),item.productName,cop(Number(item.unitPrice||0)),cop(Number(item.lineTotal??Number(item.quantity)*Number(item.unitPrice||0)))];vals.forEach((v,i)=>{page.drawRectangle({x,y,width:widths[i],height:18,borderColor:rgb(.8,.8,.8),borderWidth:.8});label(page,i===1?bold:font,fit(v,i===1?62:16),x+3,y+5,7);x+=widths[i]});y-=18});const subtotal=Number(q.subtotal||items.reduce((s,a)=>s+Number(a.quantity)*Number(a.unitPrice||0),0)),tax=Number(q.tax||0),total=subtotal+tax;
 const infoY=Math.max(244,y-54);page.drawRectangle({x:42,y:infoY,width:384,height:54,borderColor:rgb(.8,.8,.8),borderWidth:.8});label(page,font,"Especialistas en mantenimiento preventivo y correctivo de equipos biomédicos en el sector de la",45,infoY+38,6.8);label(page,font,"salud visual. Comprometidos con la calidad y seguridad en cada intervención para asegurar el óptimo",45,infoY+26,6.8);label(page,font,"funcionamiento de sus equipos, prolongando su vida útil y garantizando un servicio confiable.",45,infoY+14,6.8);[["SUBTOTAL:",subtotal],["IMPUESTOS:",tax],["TOTAL:",total]].forEach((r,i)=>{page.drawRectangle({x:426,y:infoY+36-i*18,width:124,height:18,borderColor:rgb(.8,.8,.8),borderWidth:.8});label(page,bold,r[0] as string,430,infoY+41-i*18,7);label(page,font,cop(Number(r[1])),480,infoY+41-i*18,7)});line(page,font,bold,"CANTIDAD EN LETRAS:",`${words(total)} Pesos COP`,42,infoY-20,508);
 const condY=infoY-92;page.drawRectangle({x:42,y:condY+55,width:508,height:16,color:gray});label(page,bold,"CONDICIONES DEL SERVICIO",210,condY+60,8,white);page.drawRectangle({x:42,y:condY,width:508,height:55,borderColor:black,borderWidth:.8});const conditions=String(q.serviceConditions||"1. Se debe realizar un anticipo correspondiente al 100% del valor cotizado para agendar la prestación del servicio.\n2. Una vez aceptada la cotización, la programación está sujeta a disponibilidad de agenda.").split("\n");conditions.slice(0,3).forEach((v,i)=>label(page,font,fit(v,115),46,condY+39-i*15,7));label(page,bold,"REMITE COTIZACIÓN:",44,condY-20,8);label(page,bold,"RECIBE:",360,condY-20,8);page.drawLine({start:{x:42,y:condY-58},end:{x:255,y:condY-58},thickness:1,color:black});page.drawLine({start:{x:360,y:condY-58},end:{x:550,y:condY-58},thickness:1,color:black});label(page,bold,"JD Soluciones Biomédicas",44,condY-71,8);label(page,font,"Representante: Jeyson Mendoza M.",44,condY-84,7);label(page,font,`Cliente: ${fit(q.companyName||q.customerName,38)}`,362,condY-71,7);footer(page,font,1,1,"F-COT-001.FOR r.0 2025-04");return doc.save()}
