import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const userProfiles = sqliteTable("user_profiles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  role: text("role", { enum: ["owner", "admin"] }).notNull(),
  company: text("company").notNull(),
  status: text("status", { enum: ["active", "inactive"] }).notNull().default("active"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const appUsers = sqliteTable("app_users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  role: text("role", { enum: ["superowner", "owner", "admin"] }).notNull(),
  company: text("company").notNull(),
  passwordHash: text("password_hash"),
  passwordSalt: text("password_salt"),
  activationHash: text("activation_hash").unique(),
  activationUsed: integer("activation_used", { mode: "boolean" }).notNull().default(false),
  status: text("status", { enum: ["active", "inactive"] }).notNull().default("active"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const appSessions = sqliteTable("app_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  tokenHash: text("token_hash").notNull().unique(),
  userId: integer("user_id").notNull().references(() => appUsers.id, { onDelete: "cascade" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const companies = sqliteTable("companies", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  status: text("status", { enum: ["active", "pending", "inactive"] }).notNull().default("pending"),
  city: text("city").notNull(),
  representative: text("representative").notNull(),
  phone: text("phone"),
  nit: text("nit").unique(),
  representativeEmail: text("representative_email"),
  department: text("department"),
  municipality: text("municipality"),
  billedTotal: integer("billed_total").notNull().default(0),
  outstandingBalance: integer("outstanding_balance").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const equipment = sqliteTable("equipment", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  companyId: integer("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  brand: text("brand"),
  model: text("model"),
  serialNumber: text("serial_number"),
  location: text("location"),
  purchaseDate: integer("purchase_date", { mode: "timestamp" }),
  contactName: text("contact_name"),
  ownerName: text("owner_name"),
  supplierName: text("supplier_name"),
  supplierAddress: text("supplier_address"),
  supplierPhone: text("supplier_phone"),
  supplierEmail: text("supplier_email"),
  requiresMetrology: integer("requires_metrology", { mode: "boolean" }).notNull().default(false),
  calibrationFrequency: text("calibration_frequency"),
  technicalDocuments: text("technical_documents"),
  observations: text("observations"),
  evidenceKey: text("evidence_key"),
  evidenceFileName: text("evidence_file_name"),
  evidenceContentType: text("evidence_content_type"),
  status: text("status", { enum: ["operational", "maintenance", "inactive"] }).notNull().default("operational"),
  registeredAt: integer("registered_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const serviceReports = sqliteTable("service_reports", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  equipmentId: integer("equipment_id").notNull().references(() => equipment.id, { onDelete: "cascade" }),
  code: text("code").notNull().unique(),
  serviceType: text("service_type").notNull(),
  status: text("status", { enum: ["pending", "scheduled", "in_progress", "completed"] }).notNull().default("pending"),
  technician: text("technician").notNull(),
  summary: text("summary").notNull(),
  observations: text("observations"),
  serviceValue: integer("service_value").notNull().default(0),
  serviceDate: integer("service_date", { mode: "timestamp" }).notNull(),
  startTime: text("start_time"),
  endTime: text("end_time"),
  clientPhone: text("client_phone"),
  equipmentDescription: text("equipment_description"),
  equipmentModel: text("equipment_model"),
  equipmentBrand: text("equipment_brand"),
  equipmentSerial: text("equipment_serial"),
  reportedFaultCode: text("reported_fault_code"),
  foundFaultCode: text("found_fault_code"),
  serviceDetail: text("service_detail"),
  calibrationVerified: integer("calibration_verified", { mode: "boolean" }).notNull().default(false),
  calibrationMeasurements: text("calibration_measurements"),
  receivedBy: text("received_by"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});
